language: java
jdk:
  - oraclejdk8
install: /bin/true # skip gradle assemble
before_install:
  - wget https://releases.hashicorp.com/vault/0.3.1/vault_0.3.1_linux_386.zip
  - unzip vault_0.3.1_linux_386.zip
  - ./vault server -dev &
  - VAULT_ADDR='http://127.0.0.1:8200' ./vault write secret/keyOne value=secretNumberOne
  - VAULT_ADDR='http://127.0.0.1:8200' ./vault write secret/keyTwo value=secretNumberTwo
  - VAULT_ADDR='http://127.0.0.1:8200' ./vault write secret/keyThree value=secretNumberThree
  - VAULT_ADDR='http://127.0.0.1:8200' ./vault read secret/keyOne
script: gradle check
